//get ArticleData
export const FETCH_ARTICLE_DATA = "FETCH_ARTICLE_DATA";
export const FETCH_ARTICLE_DATA_SUCCESS = "FETCH_ARTICLE_DATA_SUCCESS";
export const FETCH_ARTICLE_DATA_FAILED = "FETCH_ARTICLE_DATA_FAILED";

export const FETCH_ALL_TEACHERS = "FETCH_ALL_TEACHERS";
export const FETCH_ALL_TEACHERS_SUCCESS = "FETCH_ALL_TEACHERS_SUCCESS";
export const FETCH_ALL_TEACHERS_FAILED = "FETCH_ALL_TEACHERS_FAILED";
//Register user
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED";
//login User
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";
//get user
export const GET_USER = "GET_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_DATA_FAILED = "GET_USER_DATA_FAILED";
//Delete User Account
export const DELETE_USER_ACCOUNT = "DELETE_USER_ACCOUNT";
export const DELETE_USER_ACCOUNT_SUCCESS = "DELETE_USER_ACCOUNT";
export const DELETE_USER_ACCOUNT_FAILED = "DELETE_USER_ACCOUNT";
//Adding article Data
export const Add_ARTICLE_DATA = "Add_ARTICLE_DATA";
export const Add_ARTICLE_DATA_SUCCESS = "Add_ARTICLE_DATA_SUCCESS";
export const Add_ARTICLE_DATA_FAILED = "Add_ARTICLE_DATA_FAILED";
//Delete Article Data
export const DELETE_ARTICLE_DATA = "DELETE_ARTICLE_DATA";
export const DELETE_ARTICLE_DATA_SUCCESS = "DELETE_ARTICLE_DATA_SUCCESS";
export const DELETE_ARTICLE_DATA_FAILED = "DELETE_ARTICLE_DATA_FAILED";
//update courseDAta
export const UPDATE_ARTICLE_DATA = "UPDATE_ARTICLE_DATA";
export const UPDATE_ARTICLE_DATA_SUCCESS = "UPDATE_ARTICLE_DATA_SUCCESS";
export const UPDATE_ARTICLE_DATA_FAILED = "UPDATE_ARTICLE_DATA_FAILED";

export const FIND_DATA_BYID = "FIND_DATA_BYID";
export const FIND_DATA_BYID_SUCCESS = "FIND_DATA_BYID_SUCCESS";
export const FIND_DATA_BYID_FAILED = "FIND_DATA_BYID_FAILED";

// Changing language type
export const CHANGE_TO_CHAKMALANGUAGE = "CHANGE_TO_CHAKMALANGUAGE";

//Tur guide
export const GET_ALL_TOUR_GUIDE = "GET_ALL_TOUR_GUIDE";
export const GET_ALL_TOUR_GUIDE_SUCCESS = "GET_ALL_TOUR_GUIDE_SUCCESS";
export const GET_ALL_TOUR_GUIDE_FAILED = "GET_ALL_TOUR_GUIDE_FAILED";

// find tour guides by place  and district

export const FIND_TOURGUIDES_BY_PLACE_AND_DISTRICT =
  "FIND_TOURGUIDE_BY_PLACE_AND_DISTRICT";
export const FIND_TOURGUIDES_BY_PLACE_AND_DISTRICT_SUCCESS =
  "FIND_TOURGUIDES_BY_PLACE_AND_DISTRICT_SUCCESS";

export const FIND_TOURGUIDES_BY_PLACE_AND_DISTRICT_FAILED =
  "FIND_TOURGUIDES_BY_PLACE_AND_DISTRICT_FAILED";

//Add tour guide
export const ADD_TOUR_GUIDE = "ADD_TOUR_GUIDE";
export const ADD_TOUR_GUIDE_SUCCESS = "ADD_TOUR_GUIDE_SUCCESS";
export const ADD_TOUR_GUIDE_FAILED = "ADD_TOUR_GUIDE_FAILED";

export const GET_PLACE_BY_DISTRICT = "GET_PLACE_BY_DISTRICT";
export const GET_PLACE_BY_DISTRICT_SUCCESS = "GET_PLACE_BY_DISTRICT_SUCCESS";
export const GET_PLACE_BY_DISTRICT_FAILED = "GET_PLACE_BY_DISTRICT_FAILED";

//Delete tour guide
export const DELETE_TOUR_GUIDE = "DELETE_TOUR_GUIDE";
export const DELETE_TOUR_GUIDE_SUCCESS = "DELETE_TOUR_GUIDE_SUCCESS";
export const DELETE_TOUR_GUIDE_FAILED = "DELETE_TOUR_GUIDE_FAILED";

//Edit tour guide by admin
export const EDIT_TOUR_GUIDE = "EDIT_TOUR_GUIDE";
export const EDIT_TOUR_GUIDE_SUCCESS = "EDIT_TOUR_GUIDE_SUCCESS";
export const EDIT_TOUR_GUIDE_FAILED = "EDIT_TOUR_GUIDE_FAILED";

//edit tour guide by guide
export const EDIT_TOUR_GUIDE_BYTOURGUIDE = "EDIT_TOUR_GUIDE_BYTOURGUIDE";
export const EDIT_TOUR_GUIDE_BYTOURGUIDE_SUCCESS =
  "EDIT_TOUR_GUIDE_BYTOURGUIDE_SUCCESS";
export const EDIT_TOUR_GUIDE_BYTOURGUIDE__FAILED =
  "EDIT_TOUR_GUIDE_BYTOURGUIDE__FAILED";

//Find tourguide by id
export const FIND_TOUR_GUIDEBY_ID = "FIND_TOUR_GUIDEBY_ID";
export const FIND_TOUR_GUIDEBY_ID_SUCCESS = "FIND_TOUR_GUIDEBY_ID_SUCCESS";
export const FIND_TOUR_GUIDEBY_ID_FAILED = "FIND_TOUR_GUIDEBY_ID_FAILED";

//find tourguide by email
export const FIND_TOUR_GUIDEBY_EMAIL = "FIND_TOUR_GUIDEBY_EMAIL";
export const FIND_TOUR_GUIDEBY_EMAIL_SUCCESS = "FIND_TOUR_GUIDEBY_EMAIL_SUCCESS";
export const FIND_TOUR_GUIDEBY_EMAIL_FAILED = "FIND_TOUR_GUIDEBY_EMAIL_FAILED";

//Gets all review
export const GET_REVIEWS = "GET_REVIEWS";
export const GET_REVIEWS_SUCCESS = "GET_REVIEWS_SUCCESS";
export const GET_REVIEWS_FAILED = "GET_REVIEWS_FAILED";

//add reviw
export const ADD_REVIEW = "ADD_REVIEW";
export const ADD_REVIEW_SUCCESS = "ADD_REVIEW_SUCCESS";
export const ADD_REVIEW_FAILED = "ADD_REVIEW_FAILED";

//rmovoe remove by admin
export const REMOVE_REVIEW = "REMOVE_REVIEW";
export const REMOVE_REVIEW_SUCCESS = "REMOVE_REVIEW_SUCCESS";
export const REMOVE_REVIEW_FAILED = "REMOVE_REVIEW_FAILED";

//update review
export const UPDATE_REVIEW = "UPDATE_REVIEW";
export const UPDATE_REVIEW_SUCCESS = "UPDATE_REVIEW_SUCCESS";
export const UPDATE_REVIEW_FAILED = "UPDATE_REVIEW_FAILED";
//find by email

export const GET_REVIEW_BYMAIL = "GET_REVIEW_BYMAIL";
export const GET_REVIEW_BYMAIL_SUCCESS = "GET_REVIEW_BYMAIL_SUCCESS";
export const GET_REVIEW_BYMAIL_FAILED = "GET_REVIEW_BYMAIL_FAILED";
